export default {
  genres: [
    { id: 28, name: "Ação" },
    { id: 12, name: "Aventura" },
    { id: 16, name: "Animação" },
    { id: 35, name: "Comédia" },
    { id: 80, name: "Crime" },
    { id: 99, name: "Documentario" },
    { id: 18, name: "Drama" },
    { id: 10751, name: "Familia" },
    { id: 14, name: "Fantasia" },
    { id: 36, name: "Historia" },
    { id: 27, name: "Horror" },
    { id: 10402, name: "Musica" },
    { id: 9648, name: "Misterio" },
    { id: 10749, name: "Romance" },
    { id: 878, name: "Ficção Cientifica" },
    { id: 10770, name: "Filmes de TV" },
    { id: 53, name: "Thriller" },
    { id: 10752, name: "Guera" },
    { id: 37, name: "Ocidental" },
    { id: 10759, name: "Ação e Aventura" },
    { id: 10762, name: "Infantil" },
    { id: 10763, name: "Novos" },
    { id: 10764, name: "Reais" },
    { id: 10765, name: "Sci-Fi & Fantasia" },
    { id: 10766, name: "Comedia Romantica" },
    { id: 10767, name: "Talk Show" },
    { id: 10768, name: "Guerra e Politica" },
  ],
};
